In [14]:
import pandas as pd
import numpy as np

In [15]:
from google.colab import files
uploaded = files.upload()

Saving StudentsPerformance.csv to StudentsPerformance (2).csv

In [16]:
df = pd.read_csv(next(iter(uploaded)))

In [17]:
print("First 5 rows:")
display(df.head())

First 5 rows:

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [19]:
categorical_features = [
    'gender',
    'race/ethnicity',
    'parental level of education',
    'lunch',
    'test preparation course'
]

for col in categorical_features:
    df[col] = df[col].astype(str).str.strip().str.title()

In [20]:
score_columns = [
    'math score',
    'reading score',
    'writing score'
]

In [21]:
for col in score_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [22]:
statistics = df[score_columns].describe()

print("\nStatistical Measures:")
display(statistics)

Statistical Measures:

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [23]:
print("\nMedian:")
print(df[score_columns].median())

Median:
math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

In [24]:
df['Total Marks'] = df[score_columns].sum(axis=1)

In [25]:
df['Percentage'] = (df['Total Marks'] / 300) * 100

In [26]:
print("\nExtreme Performance Outliers:")

for col in score_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_limit) | (df[col] > upper_limit)]

    print("\n", col)
    print("Lower Limit:", lower_limit)
    print("Upper Limit:", upper_limit)
    print("Number of Outliers:", len(outliers))

Extreme Performance Outliers:

 math score
Lower Limit: 27.0
Upper Limit: 107.0
Number of Outliers: 8

 reading score
Lower Limit: 29.0
Upper Limit: 109.0
Number of Outliers: 6

 writing score
Lower Limit: 25.875
Upper Limit: 110.875
Number of Outliers: 5

In [27]:
print("\nFinal Dataset:")
display(df.head(10))

Final Dataset:

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Marks,Percentage
0,Female,Group B,Bachelor'S Degree,Standard,None,72,72,74,218,72.666667
1,Female,Group C,Some College,Standard,Completed,69,90,88,247,82.333333
2,Female,Group B,Master'S Degree,Standard,None,90,95,93,278,92.666667
3,Male,Group A,Associate'S Degree,Free/Reduced,None,47,57,44,148,49.333333
4,Male,Group C,Some College,Standard,None,76,78,75,229,76.333333
5,Female,Group B,Associate'S Degree,Standard,None,71,83,78,232,77.333333
6,Female,Group B,Some College,Standard,Completed,88,95,92,275,91.666667
7,Male,Group B,Some College,Free/Reduced,None,40,43,39,122,40.666667
8,Male,Group D,High School,Free/Reduced,Completed,64,64,67,195,65.000000
9,Female,Group B,High School,Free/Reduced,None,38,60,50,148,49.333333